// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYGM1gx8-7NclLFJEPL5FUfYqb3Re62I4',
    appId: '1:176374440980:web:8d0e1ff9e4ff3e147af301',
    messagingSenderId: '176374440980',
    projectId: 'first-project-8a707',
    authDomain: 'first-project-8a707.firebaseapp.com',
    databaseURL: 'https://first-project-8a707-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-8a707.appspot.com',
    measurementId: 'G-MBDZ41FDMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCDCddbrDjVpKobRZJVzXUGrBWPRL2jQE',
    appId: '1:176374440980:android:4b370a875ff748d17af301',
    messagingSenderId: '176374440980',
    projectId: 'first-project-8a707',
    databaseURL: 'https://first-project-8a707-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-8a707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRrGIqKxEr-PrwyVGvOMA6unbYGLo_yo',
    appId: '1:176374440980:ios:8ec3941e5e59db2b7af301',
    messagingSenderId: '176374440980',
    projectId: 'first-project-8a707',
    databaseURL: 'https://first-project-8a707-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-8a707.appspot.com',
    iosBundleId: 'com.example.chatterBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRrGIqKxEr-PrwyVGvOMA6unbYGLo_yo',
    appId: '1:176374440980:ios:8ec3941e5e59db2b7af301',
    messagingSenderId: '176374440980',
    projectId: 'first-project-8a707',
    databaseURL: 'https://first-project-8a707-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-8a707.appspot.com',
    iosBundleId: 'com.example.chatterBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYGM1gx8-7NclLFJEPL5FUfYqb3Re62I4',
    appId: '1:176374440980:web:d4a49637d52b85dd7af301',
    messagingSenderId: '176374440980',
    projectId: 'first-project-8a707',
    authDomain: 'first-project-8a707.firebaseapp.com',
    databaseURL: 'https://first-project-8a707-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-8a707.appspot.com',
    measurementId: 'G-2TYTXLT5V8',
  );
}
